apiVersion: v1
kind: PersistentVolume
metadata:
  name: geoserverdata
  labels:
    type: local
spec:
  storageClassName: {{ .Values.pv.local.storageClassName }}
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "{{ .Values.pv.local.hostPath }}"