apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoserverdata
spec:
  storageClassName: {{ .Values.pv.local.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi