apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "geoserver-chart.fullname" . }}
  labels:
    {{- include "geoserver-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "geoserver-chart.selectorLabels" . | nindent 6 }}
  serviceName: "geoserver"
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "geoserver-chart.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        volumeMounts:
        - name: www
          mountPath: /geoserver_data/data
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi