name: Lint and Kube validation

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Run chart-testing (lint)
        id: lint
        # Support for Helm 2 is on branch dev-v2.
        uses: helm/chart-testing-action@dev-v2
        with:
          command: lint

  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Kubernetes toolset
        uses: stefanprodan/kube-tools@v1.5.0
        with:
          kubectl: 1.15.10
          helm: 2.16.0
          command: helm template . | kubeval -v 1.15.0
