name: CI

on:
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Helm v2.16.0
      - name: Setup Helm v2.16.0
        run: |
          curl -LO https://get.helm.sh/helm-v2.16.0-linux-amd64.tar.gz
          tar -zxvf helm-v2.16.0-linux-amd64.tar.gz
          ./linux-amd64/helm init --client-only
      # Runs Helm linter
      - name: Run Linter
        run: ./linux-amd64/helm lint .

      # Create Package
      - name: Create Helm package
        run: ./linux-amd64/helm package .
